version: '3'
services:
  frontend:
    build:
      context: ./fullstack-frontend 
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./fullstack-backend 
    ports:
      - "8080:8080" 
      